package com.libris.testsupport;

import com.libris.book.Book;
import com.libris.loan.Loan;
import com.libris.loan.LoanProperties;
import com.libris.user.AppUser;
import com.libris.user.UserRole;
import java.lang.reflect.Field;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;

/**
 * Builders for the objects the tests keep needing.
 *
 * <p>Time is pinned to a fixed instant everywhere so that assertions about due dates,
 * reminder windows and the 90-day overdue window are deterministic rather than dependent
 * on the day the suite happens to run.
 */
public final class TestFixtures {

    public static final ZoneId ZONE = ZoneId.of("UTC");
    public static final LocalDate TODAY = LocalDate.of(2026, 8, 11);
    public static final Instant NOW = TODAY.atStartOfDay(ZONE).toInstant();

    private TestFixtures() {
    }

    public static Clock fixedClock() {
        return Clock.fixed(NOW, ZONE);
    }

    public static Clock clockAt(LocalDate date) {
        return Clock.fixed(date.atStartOfDay(ZONE).toInstant(), ZONE);
    }

    public static LoanProperties defaultLoanProperties() {
        return new LoanProperties(14, 3, 3, 2, 3, 90, 7);
    }

    public static AppUser user(String email) {
        return withId(new AppUser("Lectora de Prueba", email, "$2a$10$hash", UserRole.BIBLIOTECARIO), 1L);
    }

    public static AppUser admin(String email) {
        return withId(new AppUser("Administradora", email, "$2a$10$hash", UserRole.ADMIN), 2L);
    }

    public static Book book(String title, String isbn) {
        return withId(new Book(title, "Autora de Prueba", isbn, 2020), 10L);
    }

    public static Book bookWithSubjects(String title, String isbn, String... subjects) {
        Book book = book(title, isbn);
        book.replaceSubjects(List.of(subjects));
        return book;
    }

    /** A loan taken {@code daysAgo} and still out. */
    public static Loan openLoan(Book book, AppUser borrower, int daysAgo) {
        LocalDate loanDate = TODAY.minusDays(daysAgo);
        return withId(new Loan(book, borrower.getName(), borrower.getEmail(), loanDate, loanDate.plusDays(14)), 100L);
    }

    /** A loan already returned, late or on time depending on {@code daysLate}. */
    public static Loan returnedLoan(Book book, AppUser borrower, int daysAgo, int daysLate) {
        Loan loan = openLoan(book, borrower, daysAgo);
        loan.markReturned(loan.getDueDate().plusDays(daysLate));
        return loan;
    }

    /**
     * Entity identifiers are generated by the database, so unit tests that never touch one
     * have to set them by hand. Confined to this helper on purpose.
     */
    public static <T> T withId(T entity, Long id) {
        try {
            Field field = findField(entity.getClass(), "id");
            field.setAccessible(true);
            field.set(entity, id);
            return entity;
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("No se pudo asignar el id de prueba", e);
        }
    }

    private static Field findField(Class<?> type, String name) throws NoSuchFieldException {
        Class<?> current = type;
        while (current != null) {
            try {
                return current.getDeclaredField(name);
            } catch (NoSuchFieldException ignored) {
                current = current.getSuperclass();
            }
        }
        throw new NoSuchFieldException(name);
    }
}
